#!/usr/bin/env sh
#
# Für Seiten mit genau einem Treffer TSV mit ID, Name, Seite erstellen.
#
echo "id\tName\tSeite" > id-name-seite.tsv

cat trefferzahlen\
| grep " 1 v"\
| sed -e "s/.*\([0-9][0-9][0-9]\).*/\1/"\
| xargs -I GAGA sh -c 'echo "`cut -f3,6 volltext/GAGA.html.text.name.matches`\tGAGA"'\
>> id-name-seite.tsv
